ENVS := integration acceptance production
RENDERERS := providerconfig postgres redis

.PHONY: render render-all fmt vet check clean

# Render one environment to manifests/generated/<env>/.
# Usage: make render ENV=production
# One renderer per resource, each to its own file.
render:
	@if [ -z "$(ENV)" ]; then echo "Usage: make render ENV=<integration|acceptance|production>"; exit 1; fi
	@OUT=manifests/generated/$(ENV); mkdir -p $$OUT; \
	for r in $(RENDERERS); do \
		{ echo "# Generated by 'make render ENV=$(ENV)'. Do not edit."; \
		  kcl run -D env=$(ENV) kcl/render/$$r.k; } > $$OUT/$$r.yaml; \
	done; \
	echo "→ $$OUT/"

# Render every environment
render-all:
	@for env in $(ENVS); do $(MAKE) --no-print-directory render ENV=$$env; done

# Validate every environment renders (and passes its checks) without writing output
vet:
	@for env in $(ENVS); do \
		for r in $(RENDERERS); do \
			kcl run -D env=$$env kcl/render/$$r.k > /dev/null || exit 1; \
		done; \
	done
	@echo "✓ all environments render"

# Format all KCL source
fmt:
	kcl fmt kcl

# Fail if the committed manifests/generated is stale relative to the source.
# Renders to a temp dir and diffs, so it works with or without git (CI runs it too).
check:
	@tmp=$$(mktemp -d); \
	for env in $(ENVS); do mkdir -p $$tmp/$$env; \
		for r in $(RENDERERS); do \
			{ echo "# Generated by 'make render ENV=$$env'. Do not edit."; \
			  kcl run -D env=$$env kcl/render/$$r.k; } > $$tmp/$$env/$$r.yaml; \
		done; \
	done; \
	if diff -r $$tmp manifests/generated >/dev/null; then \
		echo "✓ manifests/generated matches source"; rm -rf $$tmp; \
	else \
		echo "✗ manifests/generated is stale — run 'make render-all' and commit"; rm -rf $$tmp; exit 1; \
	fi

clean:
	rm -rf manifests/generated
